using System;
using System.IO;
using System.Text;
using System.Threading.Tasks;

namespace ChamiUI.BusinessLayer.Exporters
{
    public class EnvironmentPowerShellScriptExporter : IPreviewableChamiExporter
    {
        public EnvironmentPowerShellScriptExporter(ScriptExportInfo scriptExportInfo)
        {
            _scriptExportInfo = scriptExportInfo;
        }
        public void Export(string filename)
        {
            ExportAsync(filename).GetAwaiter().GetResult();
        }

        public Task ExportAsync(string filename)
        {
            var stream = GetStream();

            var streamReader = new StreamReader(stream);
            File.WriteAllTextAsync(filename, streamReader.ReadToEnd());
            return Task.CompletedTask;
        }

        public string GetPreview()
        {
            return GetPreviewAsync().GetAwaiter().GetResult();
        }

        public Task<string> GetPreviewAsync()
        {
            var stream = GetStream();
            var streamReader = new StreamReader(stream);
            stream.Seek(0, SeekOrigin.Begin);
            return streamReader.ReadToEndAsync();
        }

        private readonly ScriptExportInfo _scriptExportInfo;

        private Stream GetStream()
        {
            var stream = new MemoryStream();
            var sw = new StreamWriter(stream);
            sw.AutoFlush = true;
            var generationDate = DateTime.Now;

            var generationMessage = $"# Generated by Chami on {generationDate:u}";
            sw.WriteLine(generationMessage);

            var remarks = _scriptExportInfo.Remarks;
            if (!string.IsNullOrWhiteSpace(remarks))
            {
                WriteRemarks(sw, remarks);
            }
            sw.WriteLine();
            sw.WriteLine();
            
            sw.WriteLine($"Write-Output \"Switching environment to {_scriptExportInfo.Environment.Name}\"");

            foreach (var environmentVariable in _scriptExportInfo.Environment.EnvironmentVariables)
            {
                var variableName = environmentVariable.Name;
                var variableValue = environmentVariable.Value;
                
                sw.WriteLine($"Write-Output \"Setting {variableName} to {variableValue}\"");
                
                sw.WriteLine($"$Env:{variableName}\" = \"{variableValue}\"");
                sw.WriteLine();
            }
            
            sw.WriteLine("Write-Output Execution complete");

            stream.Seek(0, SeekOrigin.Begin);

            return stream;
        }
        
        private void WriteRemarks(StreamWriter sw, string remarks)
        {
            var remarksLength = remarks.Length;
            var charIdx = 0;
            StringBuilder fullStringBuilder = new StringBuilder();
           
            while (charIdx < remarksLength)
            {
                StringBuilder stringBuilder = new StringBuilder();
                stringBuilder.Append("# ");
                while (charIdx < remarksLength && stringBuilder.Length < _scriptExportInfo.MaxLineLength - 1)
                {
                    stringBuilder.Append(remarks[charIdx]);
                    charIdx++;
                }

                fullStringBuilder.AppendLine(stringBuilder.ToString());
            }


            sw.Write(fullStringBuilder.ToString());
        }
    }
}