//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamiUI.Localization {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChamiUIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChamiUIStrings() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChamiUI.Localization.ChamiUIStrings", typeof(ChamiUIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chami.
        /// </summary>
        public static string AboutBoxApplicationName {
            get {
                return ResourceManager.GetString("AboutBoxApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Developed by Andrea Luciano Damico.
        /// </summary>
        public static string AboutBoxFirstLine_Content {
            get {
                return ResourceManager.GetString("AboutBoxFirstLine_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Flag icons provided by Panayiotis Lipiridis (https://lipis.dev).
        /// </summary>
        public static string AboutBoxFourthLine {
            get {
                return ResourceManager.GetString("AboutBoxFourthLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Released under the terms of the MIT License.
        /// </summary>
        public static string AboutBoxLicense {
            get {
                return ResourceManager.GetString("AboutBoxLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OK.
        /// </summary>
        public static string AboutBoxOkButton_Content {
            get {
                return ResourceManager.GetString("AboutBoxOkButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chami Icon by Vitaly Gorbachev.
        /// </summary>
        public static string AboutBoxSecondLine_Content {
            get {
                return ResourceManager.GetString("AboutBoxSecondLine_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://www.flaticon.com/authors/vitaly-gorbachev.
        /// </summary>
        public static string AboutBoxThirdLine {
            get {
                return ResourceManager.GetString("AboutBoxThirdLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a About Chami....
        /// </summary>
        public static string AboutMenuItem_Header {
            get {
                return ResourceManager.GetString("AboutMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add.
        /// </summary>
        public static string AddApplicationButton_Content {
            get {
                return ResourceManager.GetString("AddApplicationButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Specify an application to watch for!.
        /// </summary>
        public static string AddWatchedApplicationNullApplicationNameErrorMessage {
            get {
                return ResourceManager.GetString("AddWatchedApplicationNullApplicationNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sorting.
        /// </summary>
        public static string AdvancedSortAndFilterOptionsExpander_Header {
            get {
                return ResourceManager.GetString("AdvancedSortAndFilterOptionsExpander_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Click to show advanced sorting options..
        /// </summary>
        public static string AdvancedSortAndFilterOptionsExpander_Tooltip {
            get {
                return ResourceManager.GetString("AdvancedSortAndFilterOptionsExpander_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All environments.
        /// </summary>
        public static string AllEnvironmentsRadioButton {
            get {
                return ResourceManager.GetString("AllEnvironmentsRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All files were rejected!.
        /// </summary>
        public static string AllFilesRejectedCaption {
            get {
                return ResourceManager.GetString("AllFilesRejectedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All the files you tried to import were rejected!.
        /// </summary>
        public static string AllFilesRejectedText {
            get {
                return ResourceManager.GetString("AllFilesRejectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All supported formats.
        /// </summary>
        public static string AllSupportedFilesFileDialogDescription {
            get {
                return ResourceManager.GetString("AllSupportedFilesFileDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Console.
        /// </summary>
        public static string AppearanceSettingsGroupbox_Header {
            get {
                return ResourceManager.GetString("AppearanceSettingsGroupbox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chami has detected that the following applications are currently running:.
        /// </summary>
        public static string ApplicationsDetectedFirstParagraph_Text {
            get {
                return ResourceManager.GetString("ApplicationsDetectedFirstParagraph_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chami can try and close those applications for you, or you could close them manually. Once done, click &quot;Close&quot;..
        /// </summary>
        public static string ApplicationsDetectedSecondParagraph_Text {
            get {
                return ResourceManager.GetString("ApplicationsDetectedSecondParagraph_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Apply.
        /// </summary>
        public static string ApplyEnvironmentButton_Tooltip {
            get {
                return ResourceManager.GetString("ApplyEnvironmentButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a App name.
        /// </summary>
        public static string AppNameLabel_Content {
            get {
                return ResourceManager.GetString("AppNameLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Advanced.
        /// </summary>
        public static string BackgroundColorPicker_AdvancedTabHeader {
            get {
                return ResourceManager.GetString("BackgroundColorPicker_AdvancedTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Available colors.
        /// </summary>
        public static string BackgroundColorPicker_AvailableColorsHeader {
            get {
                return ResourceManager.GetString("BackgroundColorPicker_AvailableColorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Standard colors.
        /// </summary>
        public static string BackgroundColorPicker_StandardColorsHeader {
            get {
                return ResourceManager.GetString("BackgroundColorPicker_StandardColorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Standard.
        /// </summary>
        public static string BackgroundColorPicker_StandardTabHeader {
            get {
                return ResourceManager.GetString("BackgroundColorPicker_StandardTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Backup current environment.
        /// </summary>
        public static string BackupEnvironmentMenuItem_Header {
            get {
                return ResourceManager.GetString("BackupEnvironmentMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bg Color.
        /// </summary>
        public static string BgColorLabel_Content {
            get {
                return ResourceManager.GetString("BgColorLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a About Chami....
        /// </summary>
        public static string ChamiAboutBox_Title {
            get {
                return ResourceManager.GetString("ChamiAboutBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Export environments.
        /// </summary>
        public static string ChamiExportWindow_Title {
            get {
                return ResourceManager.GetString("ChamiExportWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Find....
        /// </summary>
        public static string ChamiFindWindow_Title {
            get {
                return ResourceManager.GetString("ChamiFindWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Clear filter.
        /// </summary>
        public static string ClearFilterButton_Tooltip {
            get {
                return ResourceManager.GetString("ClearFilterButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Close.
        /// </summary>
        public static string CloseDetectedApplicationsWindowButton_Content {
            get {
                return ResourceManager.GetString("CloseDetectedApplicationsWindowButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Console.
        /// </summary>
        public static string ConsoleTabItem_Header {
            get {
                return ResourceManager.GetString("ConsoleTabItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Copy.
        /// </summary>
        public static string CopyEnvironmentVariableMenuItem_Header {
            get {
                return ResourceManager.GetString("CopyEnvironmentVariableMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete?.
        /// </summary>
        public static string DataGridMarkedForDeletionColumn {
            get {
                return ResourceManager.GetString("DataGridMarkedForDeletionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete?.
        /// </summary>
        public static string DataGridMarkedForDeletionColumn_Header {
            get {
                return ResourceManager.GetString("DataGridMarkedForDeletionColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        public static string DataGridNameColumn {
            get {
                return ResourceManager.GetString("DataGridNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        public static string DataGridNameColumn_Header {
            get {
                return ResourceManager.GetString("DataGridNameColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Value.
        /// </summary>
        public static string DataGridValueColumn {
            get {
                return ResourceManager.GetString("DataGridValueColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Value.
        /// </summary>
        public static string DataGridValueColumn_Header {
            get {
                return ResourceManager.GetString("DataGridValueColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm deletion.
        /// </summary>
        public static string DeleteEnvironmentCaption {
            get {
                return ResourceManager.GetString("DeleteEnvironmentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete.
        /// </summary>
        public static string DeleteEnvironmentMenuItem_Header {
            get {
                return ResourceManager.GetString("DeleteEnvironmentMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to remove the environment {0}?.
        /// </summary>
        public static string DeleteEnvironmentNoVariablesText {
            get {
                return ResourceManager.GetString("DeleteEnvironmentNoVariablesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete.
        /// </summary>
        public static string DeleteEnvironmentVariableMenuItem_Header {
            get {
                return ResourceManager.GetString("DeleteEnvironmentVariableMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to remove the environment {0} and its {1} variables?.
        /// </summary>
        public static string DeleteEnvironmentWithVariablesText {
            get {
                return ResourceManager.GetString("DeleteEnvironmentWithVariablesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Descending.
        /// </summary>
        public static string DescendingSortingCheckBox_Content {
            get {
                return ResourceManager.GetString("DescendingSortingCheckBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enable detecting the following applications are running.
        /// </summary>
        public static string DetectApplicationsCheckboxLabel_Content {
            get {
                return ResourceManager.GetString("DetectApplicationsCheckboxLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Detect applications.
        /// </summary>
        public static string DetectAppplicationsGroupbox_Header {
            get {
                return ResourceManager.GetString("DetectAppplicationsGroupbox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Detector.
        /// </summary>
        public static string DetectorCategory {
            get {
                return ResourceManager.GetString("DetectorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Restart applications!.
        /// </summary>
        public static string DetectorMessageBoxCaption {
            get {
                return ResourceManager.GetString("DetectorMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chami has detected that the following applications are currently running:.
        /// </summary>
        public static string DetectorMessageBoxTextPart1 {
            get {
                return ResourceManager.GetString("DetectorMessageBoxTextPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a It is recommended that you restart them..
        /// </summary>
        public static string DetectorMessageBoxTextPart2 {
            get {
                return ResourceManager.GetString("DetectorMessageBoxTextPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This feature is currently unavailable..
        /// </summary>
        public static string DisabledSafetyFeatureStackPanel_ToolTip {
            get {
                return ResourceManager.GetString("DisabledSafetyFeatureStackPanel_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a dotEnv files.
        /// </summary>
        public static string DotEnvFileDialogDescription {
            get {
                return ResourceManager.GetString("DotEnvFileDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit.
        /// </summary>
        public static string EditEnvironmentMenuItem_Header {
            get {
                return ResourceManager.GetString("EditEnvironmentMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enable logging.
        /// </summary>
        public static string EnableLoggingLabel_Content {
            get {
                return ResourceManager.GetString("EnableLoggingLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enable safety features.
        /// </summary>
        public static string EnableSafetyFeaturesLabel_Content {
            get {
                return ResourceManager.GetString("EnableSafetyFeaturesLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a In environment name and variable names and values.
        /// </summary>
        public static string EnvironmentAndVariableNameAndValueFilterStrategyName {
            get {
                return ResourceManager.GetString("EnvironmentAndVariableNameAndValueFilterStrategyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a In environment and variable names.
        /// </summary>
        public static string EnvironmentAndVariableNameFilterStrategyName {
            get {
                return ResourceManager.GetString("EnvironmentAndVariableNameFilterStrategyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} ({1} variables).
        /// </summary>
        public static string EnvironmentExportWindowViewModelDisplayedName {
            get {
                return ResourceManager.GetString("EnvironmentExportWindowViewModelDisplayedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a In environment name.
        /// </summary>
        public static string EnvironmentNameFilterStrategyName {
            get {
                return ResourceManager.GetString("EnvironmentNameFilterStrategyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You must specify an environment name!.
        /// </summary>
        public static string EnvironmentNameValidationErrorMessage {
            get {
                return ResourceManager.GetString("EnvironmentNameValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Conversion from format {0} is not supported..
        /// </summary>
        public static string EnvironmentReaderFactoryNotSupportedMessage {
            get {
                return ResourceManager.GetString("EnvironmentReaderFactoryNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The environment variable name contains invalid characters at positions {0}..
        /// </summary>
        public static string EnvironmentVariableNameInvalidCharactersErrorMessage {
            get {
                return ResourceManager.GetString("EnvironmentVariableNameInvalidCharactersErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The environment variable name contains an invalid character at position {0}..
        /// </summary>
        public static string EnvironmentVariableNameInvalidCharactersErrorMessageSingular {
            get {
                return ResourceManager.GetString("EnvironmentVariableNameInvalidCharactersErrorMessageSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An environment variable name has a maximum length of {0} characters.
        ///Current length: {1}.
        /// </summary>
        public static string EnvironmentVariableNameLengthErrorMessage {
            get {
                return ResourceManager.GetString("EnvironmentVariableNameLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You must specify a name for the environment variable!.
        /// </summary>
        public static string EnvironmentVariableNameNotNullErrorMessage {
            get {
                return ResourceManager.GetString("EnvironmentVariableNameNotNullErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a There&apos;s already an environment variable with the name {0} in environment {1}..
        /// </summary>
        public static string EnvironmentVariableNameNotUniqueErrorMessage {
            get {
                return ResourceManager.GetString("EnvironmentVariableNameNotUniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An environment variable name may not start with a digit..
        /// </summary>
        public static string EnvironmentVariableNameNumberFirstCharacterErrorMessage {
            get {
                return ResourceManager.GetString("EnvironmentVariableNameNumberFirstCharacterErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Example text....
        /// </summary>
        public static string ExampleTextTextBox_Text {
            get {
                return ResourceManager.GetString("ExampleTextTextBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Execution complete.
        /// </summary>
        public static string ExecutionCompleteMessage {
            get {
                return ResourceManager.GetString("ExecutionCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error importing environment.
        /// </summary>
        public static string ExistingEnvironmentMessageBoxCaption {
            get {
                return ResourceManager.GetString("ExistingEnvironmentMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An environment with the same name already exists!.
        /// </summary>
        public static string ExistingEnvironmentMessageBoxText {
            get {
                return ResourceManager.GetString("ExistingEnvironmentMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chami is already running!.
        /// </summary>
        public static string ExistingInstanceMessageBoxCaption {
            get {
                return ResourceManager.GetString("ExistingInstanceMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a There&apos;s already another instance of Chami running with PID {0}.
        ///The application will now close..
        /// </summary>
        public static string ExistingInstanceMessageBoxText {
            get {
                return ResourceManager.GetString("ExistingInstanceMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Export.
        /// </summary>
        public static string ExportDataButton_Content {
            get {
                return ResourceManager.GetString("ExportDataButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Export....
        /// </summary>
        public static string ExportMenuItem_Header {
            get {
                return ResourceManager.GetString("ExportMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        public static string ExportWindowCancelButton_Content {
            get {
                return ResourceManager.GetString("ExportWindowCancelButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Export settings:.
        /// </summary>
        public static string ExportWindowGroupBox_Header {
            get {
                return ResourceManager.GetString("ExportWindowGroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Export environments.
        /// </summary>
        public static string ExportWindowHeaderTitle {
            get {
                return ResourceManager.GetString("ExportWindowHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Environment.
        /// </summary>
        public static string ExportWindowTitle {
            get {
                return ResourceManager.GetString("ExportWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Feature not supported!.
        /// </summary>
        public static string FeatureNotSupportedExceptionMessage {
            get {
                return ResourceManager.GetString("FeatureNotSupportedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FgColor.
        /// </summary>
        public static string FgColorLabel_Content {
            get {
                return ResourceManager.GetString("FgColorLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File.
        /// </summary>
        public static string FileMenuItem {
            get {
                return ResourceManager.GetString("FileMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Filter.
        /// </summary>
        public static string FilteringAdvancedOptionsGroupBox_Header {
            get {
                return ResourceManager.GetString("FilteringAdvancedOptionsGroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Case sensitive.
        /// </summary>
        public static string FilteringCaseSensitivityIcon_ToolTip {
            get {
                return ResourceManager.GetString("FilteringCaseSensitivityIcon_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Case sensitive.
        /// </summary>
        public static string FilteringCaseSensitivityLabel_Content {
            get {
                return ResourceManager.GetString("FilteringCaseSensitivityLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Find in:.
        /// </summary>
        public static string FilteringStrategyLabel_Content {
            get {
                return ResourceManager.GetString("FilteringStrategyLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type to filter....
        /// </summary>
        public static string FilterTextbox_Watermark {
            get {
                return ResourceManager.GetString("FilterTextbox_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type to filter....
        /// </summary>
        public static string FilterTextBoxWatermark_Content {
            get {
                return ResourceManager.GetString("FilterTextBoxWatermark_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Find next.
        /// </summary>
        public static string FindWindowSearchButton_Content {
            get {
                return ResourceManager.GetString("FindWindowSearchButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a In environments.
        /// </summary>
        public static string FindWindowSearchInEnvironmentNameComboBoxItem_Content {
            get {
                return ResourceManager.GetString("FindWindowSearchInEnvironmentNameComboBoxItem_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a In environment variables.
        /// </summary>
        public static string FindWindowSearchInEnvironmentVariablesComboBoxItem_Content {
            get {
                return ResourceManager.GetString("FindWindowSearchInEnvironmentVariablesComboBoxItem_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Find.
        /// </summary>
        public static string FindWindowSearchTextLabel_Content {
            get {
                return ResourceManager.GetString("FindWindowSearchTextLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search in:.
        /// </summary>
        public static string FindWindowWhereToSearchLabel {
            get {
                return ResourceManager.GetString("FindWindowWhereToSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search in:.
        /// </summary>
        public static string FindWindowWhereToSearchLabel_Content {
            get {
                return ResourceManager.GetString("FindWindowWhereToSearchLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Font.
        /// </summary>
        public static string FontLabel_Content {
            get {
                return ResourceManager.GetString("FontLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Font size.
        /// </summary>
        public static string FontSizeLabel_Content {
            get {
                return ResourceManager.GetString("FontSizeLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Advanced.
        /// </summary>
        public static string ForegroundColorPicker_AdvancedTabHeader {
            get {
                return ResourceManager.GetString("ForegroundColorPicker_AdvancedTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Available colors.
        /// </summary>
        public static string ForegroundColorPicker_AvailableColorsHeader {
            get {
                return ResourceManager.GetString("ForegroundColorPicker_AvailableColorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Standard.
        /// </summary>
        public static string ForegroundColorPicker_StandardColorsHeader {
            get {
                return ResourceManager.GetString("ForegroundColorPicker_StandardColorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Standard.
        /// </summary>
        public static string ForegroundColorPicker_StandardTabHeader {
            get {
                return ResourceManager.GetString("ForegroundColorPicker_StandardTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An exception occurred!.
        /// </summary>
        public static string GenericExceptionMessageBoxCaption {
            get {
                return ResourceManager.GetString("GenericExceptionMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chami on Github.
        /// </summary>
        public static string GithubLinkMenuItem_Header {
            get {
                return ResourceManager.GetString("GithubLinkMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Import environments.
        /// </summary>
        public static string ImportEnvironmentWindowHeaderTitle_Content {
            get {
                return ResourceManager.GetString("ImportEnvironmentWindowHeaderTitle_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save.
        /// </summary>
        public static string ImportEnvironmentWindowSaveButton_Content {
            get {
                return ResourceManager.GetString("ImportEnvironmentWindowSaveButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Import environments.
        /// </summary>
        public static string ImportEnvironmentWindowTitle_Title {
            get {
                return ResourceManager.GetString("ImportEnvironmentWindowTitle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a From .env....
        /// </summary>
        public static string ImportFromDotenvMenuItem_Header {
            get {
                return ResourceManager.GetString("ImportFromDotenvMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a From JSON....
        /// </summary>
        public static string ImportFromJsonMenuItem_Header {
            get {
                return ResourceManager.GetString("ImportFromJsonMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Import.
        /// </summary>
        public static string ImportMenuItem_Header {
            get {
                return ResourceManager.GetString("ImportMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enabled?.
        /// </summary>
        public static string IsWatchEnabledColumn {
            get {
                return ResourceManager.GetString("IsWatchEnabledColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Deserialization error!.
        /// </summary>
        public static string JsonDeserializationErrorMessageBoxCaption {
            get {
                return ResourceManager.GetString("JsonDeserializationErrorMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to deserialize input file!
        ///See the log for more details..
        /// </summary>
        public static string JsonDeserializationErrorMessageBoxText {
            get {
                return ResourceManager.GetString("JsonDeserializationErrorMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Json Files.
        /// </summary>
        public static string JsonFileDialogDescription {
            get {
                return ResourceManager.GetString("JsonFileDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Language.
        /// </summary>
        public static string LanguageCategory {
            get {
                return ResourceManager.GetString("LanguageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Language.
        /// </summary>
        public static string LanguageSelectorLabel_Content {
            get {
                return ResourceManager.GetString("LanguageSelectorLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Logging.
        /// </summary>
        public static string LoggingCategory {
            get {
                return ResourceManager.GetString("LoggingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Logging.
        /// </summary>
        public static string LoggingGroupBox_Header {
            get {
                return ResourceManager.GetString("LoggingGroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit.
        /// </summary>
        public static string MainWindowEditMenuItem_Header {
            get {
                return ResourceManager.GetString("MainWindowEditMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Filter.
        /// </summary>
        public static string MainWindowFilterLabel_Content {
            get {
                return ResourceManager.GetString("MainWindowFilterLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Find.
        /// </summary>
        public static string MainWindowFindMenuItem_Header {
            get {
                return ResourceManager.GetString("MainWindowFindMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a When minimized:.
        /// </summary>
        public static string MinimizationBehaviourControlLabel_Content {
            get {
                return ResourceManager.GetString("MinimizationBehaviourControlLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Minimization.
        /// </summary>
        public static string MinimizationCategory {
            get {
                return ResourceManager.GetString("MinimizationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Minimize to Taskbar.
        /// </summary>
        public static string MinimizeToTaskbarStrategyName {
            get {
                return ResourceManager.GetString("MinimizeToTaskbarStrategyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Minimize to Tray.
        /// </summary>
        public static string MinimizeToTrayStrategyName {
            get {
                return ResourceManager.GetString("MinimizeToTrayStrategyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        public static string NewEnvironmentDataGridNameColumn {
            get {
                return ResourceManager.GetString("NewEnvironmentDataGridNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        public static string NewEnvironmentDataGridNameColumn_Header {
            get {
                return ResourceManager.GetString("NewEnvironmentDataGridNameColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Value.
        /// </summary>
        public static string NewEnvironmentDataGridValueColumn {
            get {
                return ResourceManager.GetString("NewEnvironmentDataGridValueColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        public static string NewEnvironmentFormNameLabel_Content {
            get {
                return ResourceManager.GetString("NewEnvironmentFormNameLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Environment.
        /// </summary>
        public static string NewEnvironmentMenuItem_Header {
            get {
                return ResourceManager.GetString("NewEnvironmentMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        public static string NewEnvironmentWindowCancelButton_Content {
            get {
                return ResourceManager.GetString("NewEnvironmentWindowCancelButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New environment.
        /// </summary>
        public static string NewEnvironmentWindowHeaderTitle {
            get {
                return ResourceManager.GetString("NewEnvironmentWindowHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save.
        /// </summary>
        public static string NewEnvironmentWindowSaveButton_Content {
            get {
                return ResourceManager.GetString("NewEnvironmentWindowSaveButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New environment.
        /// </summary>
        public static string NewEnvironmentWindowTitle_Title {
            get {
                return ResourceManager.GetString("NewEnvironmentWindowTitle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        public static string NewTemplateEnvironmentDataGridNameColumn {
            get {
                return ResourceManager.GetString("NewTemplateEnvironmentDataGridNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Value.
        /// </summary>
        public static string NewTemplateEnvironmentDataGridValueColumn {
            get {
                return ResourceManager.GetString("NewTemplateEnvironmentDataGridValueColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        public static string NewTemplateEnvironmentWindowCancelButton_Content {
            get {
                return ResourceManager.GetString("NewTemplateEnvironmentWindowCancelButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save.
        /// </summary>
        public static string NewTemplateEnvironmentWindowSaveButton_Content {
            get {
                return ResourceManager.GetString("NewTemplateEnvironmentWindowSaveButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New template.
        /// </summary>
        public static string NewTemplateMenuItem_Header {
            get {
                return ResourceManager.GetString("NewTemplateMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New template.
        /// </summary>
        public static string NewTemplateWindowHeaderTitle_Content {
            get {
                return ResourceManager.GetString("NewTemplateWindowHeaderTitle_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New template.
        /// </summary>
        public static string NewTemplateWindowTitle_Title {
            get {
                return ResourceManager.GetString("NewTemplateWindowTitle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An operation was cancelled!
        ///.
        /// </summary>
        public static string OperationCanceledMessage {
            get {
                return ResourceManager.GetString("OperationCanceledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reverting back to previous environment.
        ///.
        /// </summary>
        public static string OperationCanceledRevertMessage {
            get {
                return ResourceManager.GetString("OperationCanceledRevertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Options.
        /// </summary>
        public static string OptionsMenuItem_Header {
            get {
                return ResourceManager.GetString("OptionsMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Process name.
        /// </summary>
        public static string ProcessNameColumn {
            get {
                return ResourceManager.GetString("ProcessNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Quit.
        /// </summary>
        public static string QuitApplicationMenuItem_Header {
            get {
                return ResourceManager.GetString("QuitApplicationMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Exiting Chami..
        /// </summary>
        public static string QuitMessageBoxCaption {
            get {
                return ResourceManager.GetString("QuitMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to quit?.
        /// </summary>
        public static string QuitMessageBoxText {
            get {
                return ResourceManager.GetString("QuitMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Refresh.
        /// </summary>
        public static string RefreshButtonLabel_Content {
            get {
                return ResourceManager.GetString("RefreshButtonLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rename.
        /// </summary>
        public static string RenameEnvironmentMenuItem {
            get {
                return ResourceManager.GetString("RenameEnvironmentMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        public static string RenameEnvironmentNameLabel_Content {
            get {
                return ResourceManager.GetString("RenameEnvironmentNameLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OK.
        /// </summary>
        public static string RenameEnvironmentOkButton_Content {
            get {
                return ResourceManager.GetString("RenameEnvironmentOkButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rename environment.
        /// </summary>
        public static string RenameEnvironmentWindowTitle {
            get {
                return ResourceManager.GetString("RenameEnvironmentWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        public static string RenameWindowCancelButton_Content {
            get {
                return ResourceManager.GetString("RenameWindowCancelButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm.
        /// </summary>
        public static string ResetEnvironmentMessageBoxCaption {
            get {
                return ResourceManager.GetString("ResetEnvironmentMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This will remove the currently active Chami environment. Are you sure you want to proceed?.
        /// </summary>
        public static string ResetEnvironmentMessageBoxText {
            get {
                return ResourceManager.GetString("ResetEnvironmentMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reset environment variables.
        /// </summary>
        public static string ResetVarsMenuItem_Header {
            get {
                return ResourceManager.GetString("ResetVarsMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reverting back to original environment variables....
        /// </summary>
        public static string RevertToOriginalEnvironmentMessage {
            get {
                return ResourceManager.GetString("RevertToOriginalEnvironmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a There&apos;s no active Chami environment!
        ///Nothing to do..
        /// </summary>
        public static string RevertToOriginalEnvironmentNop {
            get {
                return ResourceManager.GetString("RevertToOriginalEnvironmentNop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Safety.
        /// </summary>
        public static string SafetyCategory {
            get {
                return ResourceManager.GetString("SafetyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Variables.
        /// </summary>
        public static string SafetyFeaturesVariablesLabel_Content {
            get {
                return ResourceManager.GetString("SafetyFeaturesVariablesLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Safety.
        /// </summary>
        public static string SafetyGroupbox_Header {
            get {
                return ResourceManager.GetString("SafetyGroupbox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save.
        /// </summary>
        public static string SaveEnvironmentMenuItem_Header {
            get {
                return ResourceManager.GetString("SaveEnvironmentMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selected environments.
        /// </summary>
        public static string SelectedEnvironmentsRadioButton_Content {
            get {
                return ResourceManager.GetString("SelectedEnvironmentsRadioButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settings.
        /// </summary>
        public static string SettingsMenuItem_Header {
            get {
                return ResourceManager.GetString("SettingsMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Apply.
        /// </summary>
        public static string SettingsWindowApplyButton_Content {
            get {
                return ResourceManager.GetString("SettingsWindowApplyButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        public static string SettingsWindowCancelButton_Content {
            get {
                return ResourceManager.GetString("SettingsWindowCancelButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OK.
        /// </summary>
        public static string SettingsWindowOkButton {
            get {
                return ResourceManager.GetString("SettingsWindowOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chami - Settings.
        /// </summary>
        public static string SettingsWindowTitle_Title {
            get {
                return ResourceManager.GetString("SettingsWindowTitle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a By date added.
        /// </summary>
        public static string SortByDateAddedRadioButton_Content {
            get {
                return ResourceManager.GetString("SortByDateAddedRadioButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a By date added.
        /// </summary>
        public static string SortByDateMenuItem_Header {
            get {
                return ResourceManager.GetString("SortByDateMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a By Id.
        /// </summary>
        public static string SortByIdMenuItem_Header {
            get {
                return ResourceManager.GetString("SortByIdMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a By Id.
        /// </summary>
        public static string SortByIdRadioButton_Content {
            get {
                return ResourceManager.GetString("SortByIdRadioButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a By name.
        /// </summary>
        public static string SortByNameMenuItem_Header {
            get {
                return ResourceManager.GetString("SortByNameMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a By name.
        /// </summary>
        public static string SortByNameRadioButton_Content {
            get {
                return ResourceManager.GetString("SortByNameRadioButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Descending.
        /// </summary>
        public static string SortDescendingMenuItem {
            get {
                return ResourceManager.GetString("SortDescendingMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sorting.
        /// </summary>
        public static string SortingGroupBox_Header {
            get {
                return ResourceManager.GetString("SortingGroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sorting....
        /// </summary>
        public static string SortingOptionsMenuItem_Header {
            get {
                return ResourceManager.GetString("SortingOptionsMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Starting execution....
        /// </summary>
        public static string StartingExecutionMessage {
            get {
                return ResourceManager.GetString("StartingExecutionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Exit.
        /// </summary>
        public static string TaskbarExitMenuItem {
            get {
                return ResourceManager.GetString("TaskbarExitMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hide Chami.
        /// </summary>
        public static string TaskbarHideChamiMenuItem {
            get {
                return ResourceManager.GetString("TaskbarHideChamiMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Exit.
        /// </summary>
        public static string TaskbarItemExit_Header {
            get {
                return ResourceManager.GetString("TaskbarItemExit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hide Chami.
        /// </summary>
        public static string TaskbarItemHide {
            get {
                return ResourceManager.GetString("TaskbarItemHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Show Chami.
        /// </summary>
        public static string TaskbarItemShow_Header {
            get {
                return ResourceManager.GetString("TaskbarItemShow_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Show Chami.
        /// </summary>
        public static string TaskbarShowChamiMenuItem {
            get {
                return ResourceManager.GetString("TaskbarShowChamiMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Show Chami.
        /// </summary>
        public static string TaskbarShowChamiMenuItem_Header {
            get {
                return ResourceManager.GetString("TaskbarShowChamiMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Template.
        /// </summary>
        public static string TemplateEnvironmentLabel_Content {
            get {
                return ResourceManager.GetString("TemplateEnvironmentLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Template name.
        /// </summary>
        public static string TemplateNameLabel_Content {
            get {
                return ResourceManager.GetString("TemplateNameLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Terminate all.
        /// </summary>
        public static string TerminateAllButton_Content {
            get {
                return ResourceManager.GetString("TerminateAllButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error!.
        /// </summary>
        public static string UnableToInsertEnvironmentMessageBoxCaption {
            get {
                return ResourceManager.GetString("UnableToInsertEnvironmentMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to insert your new environment!.
        /// </summary>
        public static string UnableToInsertEnvironmentMessageBoxText {
            get {
                return ResourceManager.GetString("UnableToInsertEnvironmentMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Validation error!.
        /// </summary>
        public static string ValidationFailedMessageBoxCaption {
            get {
                return ResourceManager.GetString("ValidationFailedMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The variables in the environment you&apos;re trying to save didn&apos;t pass validation.
        ///Fix the issues and try saving again..
        /// </summary>
        public static string ValidationFailedMessageBoxText {
            get {
                return ResourceManager.GetString("ValidationFailedMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Variables.
        /// </summary>
        public static string VariablesTabItem_Header {
            get {
                return ResourceManager.GetString("VariablesTabItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a View.
        /// </summary>
        public static string ViewCategory {
            get {
                return ResourceManager.GetString("ViewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Website.
        /// </summary>
        public static string WebsiteMenuItem_Header {
            get {
                return ResourceManager.GetString("WebsiteMenuItem_Header", resourceCulture);
            }
        }
    }
}
